### PR TITLE
Fixes to Basic Points for Badges component

### LINKED ISSUE #324: Basic Points For Badges - Custom Field
The [Basic Points For Badges component](https://ui.mydatahelps.org/?path=/docs/container-basicpointsforbadges--docs) can be configured against a custom field. 

The component is configured to grant a badge once a value of XX in points is earned. Activities are then configured for earning points. For example, earn 50 points for every 8 hours of sleep or 20 points for completing a survey. 

In the case of the Custom activity, the total points earned for this activity will be 
custom field * activity points and does not consider if points were already granted for any given day. The result of not limiting the earning of points to a day or other time frame is that new points are earned each time the component is initialized. If a ppt views the component multiple times a day then they will earn additional points (custom field * activity points) each instance. 

Should there be a restriction on how often points are earned against a custom field?

### PR DESCRIPTION
**Pull request by reneefromhold**
## Overview

Fixes
1) Title color property was not working
2) Added comments near where the awards url is opened. This came up while developing in Live mode and downstream repos
3) Updated the custom activity to update the custom field with recalculated points. Was previously adding recalculated points to the custom field. Fixes #324 

## Security

REMINDER: All file contents are public.

- [ ] I have ensured no secure credentials or sensitive information remain in code, metadata, comments, etc.
  - [ ] Please verify that you double checked that .storybook/preview.js does not contain your participant access key details. 
  - [ ] There are no temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [ ] These changes do not introduce any security risks, or any such risks have been properly mitigated.

Describe briefly what security risks you considered, why they don't apply, or how they've been mitigated.

### Testing
- [ ] MyDataHelps iOS app
- [ ] MyDataHelps Android app
- [ ] [MyDataHelps website](mydatahelps.org)

### Documentation
- [ ] I have added relevant Storybook updates to this PR as well.
- [ ] If this feature requires a developer doc update, tag @CareEvolution/api-docs.

Consider "Squash and merge" as needed to keep the commit history reasonable on `main`.

## Reviewers

Assign to the appropriate reviewer(s). Minimally, a second set of eyes is needed ensure no non-public information is published. Consider also including:
- Subject-matter experts
- Style/editing reviewers
- Others requested by the content owner

## Summary by CodeRabbit

- **New Features**
	- Added customizable properties for label and progress bar colors in the Basic Points for Badges component.
	- Introduced a new activity type for tracking personal goals.

- **Bug Fixes**
	- Improved state management for badges, ensuring correct updates and rendering.
	- Corrected conditional rendering for the loading indicator based on points and badges.

- **Refactor**
	- Enhanced readability of the Title component's color prop assignment.

- **Chores**
	- Updated package version to reflect new features and changes.

### CODE REVIEW

File: src/components/container/BasicPointsForBadges/BasicPointsForBadges.tsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ export default function (props: BasicPointsForBadgesProps) {
     return <div className={"mdhui-basic-points-for-badges"} ref={props.innerRef}>
         {badges !== undefined && points !== undefined &&
             <>
-                <Title order={1} className="mdhui-basic-points-for-badges-points-toward-badge" style={{ color: resolveColor(layoutContext.colorScheme, props.pointsLabelColor) }}>{props.showTotalPoints ? points.toLocaleString() : (props.pointsPerBadge - pointsUntilNextBadge()).toLocaleString()}pts</Title>
+                <Title order={1} className="mdhui-basic-points-for-badges-points-toward-badge" color={resolveColor(layoutContext.colorScheme, props.pointsLabelColor)} >{props.showTotalPoints ? points.toLocaleString() : (props.pointsPerBadge - pointsUntilNextBadge()).toLocaleString()}pts</Title>
```
Comment (greinard) [inline src/components/container/BasicPointsForBadges/BasicPointsForBadges.tsx:81]: You can just use `color={props.pointsLabelColor}` here.  The resolution of the color already occurs within the `Title` component.

Same thing below for the progress bar fill color.

Once those are updated, you can probably remove the `layoutContext` all together, as I don't think it is used anywhere else.

File: src/components/container/BasicPointsForBadges/BasicPointsForBadges.tsx [hunk 2]
```diff
@@ -78,10 +83,10 @@ export default function (props: BasicPointsForBadgesProps) {
     return <div className={"mdhui-basic-points-for-badges"} ref={props.innerRef}>
         {badges !== undefined && points !== undefined &&
             <>
-                <Title order={1} className="mdhui-basic-points-for-badges-points-toward-badge" style={{ color: resolveColor(layoutContext.colorScheme, props.pointsLabelColor) }}>{props.showTotalPoints ? points.toLocaleString() : (props.pointsPerBadge - pointsUntilNextBadge()).toLocaleString()}pts</Title>
+                <Title order={1} className="mdhui-basic-points-for-badges-points-toward-badge" color={props.pointsLabelColor} >{props.showTotalPoints ? points.toLocaleString() : (props.pointsPerBadge - pointsUntilNextBadge()).toLocaleString()}pts</Title>
                 <ProgressBar key={badges.length} // forces re-render to skip "backwards" animation when badges change
                     fillPercent={(props.pointsPerBadge - pointsUntilNextBadge()) / (props.pointsPerBadge * 1.0) * 100}
-                    fillColor={resolveColor(layoutContext.colorScheme, props.progressBarFillColor) || "var(--mdhui-color-primary)"}
+                    fillColor={props.progressBarFillColor}
```
Comment (greinard) [inline src/components/container/BasicPointsForBadges/BasicPointsForBadges.tsx:89]: I missed the `|| "var(--mdhui-color-primary)"` part when looking at this before.  We may want this to be:

```
fillColor={props.progressBarFillColor || "var(--mdhui-color-primary)"}
```

It looks like there are some default props defined in the ProgressBar with that value, but I'm not sure if that gets overridden with the `undefined` value since we are specifying. 🤔

**Comment by reneefromhold** [comment]
@greinard When you have a minute, your concerns should all be addressed. Also, note the update to the calculation for custom type. See issue #324 for discussion

**Review by greinard — APPROVED** [review]
